#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""run_modal_analysis.py

Run a CalculiX modal (eigenfrequency) analysis on the elastic dam-break gate
solid mesh generated by 01_generate_mesh.py (dam_gate.inp, 868 nodes / 540 C3D8),
extract the first ``--n-modes`` natural frequencies, and compare them against
the APDL reference modal files (FluidNodeDisp1..10.csv header frequency).

Pipeline:
    1. load the solid mesh (prefer 01_generate_mesh.build_solid_mesh / nsets,
       fall back to parsing dam_gate.inp)
    2. read material (from dam_gate.inp, overridable via --gate-e/--gate-nu/
       --gate-rho, defaults E=1e6 Pa / nu=0 / rho=2500 kg/m^3)
    3. write a modal analysis .inp (*FREQUENCY step) with the same boundary
       conditions as the FSI case (bottom fixed + z-faces constrained in z)
    4. run ``ccx -i dam_gate_modal`` in the output directory
    5. parse the eigenvalues from dam_gate_modal.dat
    6. read APDL reference frequencies from FluidNodeDisp<i>.csv
    7. print a comparison table and assert the 1st frequency ~ 6.02 Hz

Only the Python standard library is used.  No third-party dependencies.

Usage:
    python3 run_modal_analysis.py \
        --mesh-dir /root/Workspace/precice_damfailure_new/solid-calculix \
        --out-dir  /root/Workspace/precice_damfailure_modal
"""

import argparse
import importlib
import os
import shutil
import subprocess
import sys

# --------------------------------------------------------------------------- #
#  Defaults (geometry / material from CaseDescription.md, table 3-2)          #
# --------------------------------------------------------------------------- #

MESH_DIR_DEFAULT = "/root/Workspace/precice_damfailure_new/solid-calculix"
OUT_DIR_DEFAULT = "/root/Workspace/precice_damfailure_modal"
REF_CSV_DEFAULT = "/root/Workspace/tmp/opencode/damfailure_fine_symm/damfailure_fine_symm/mode"

GATE_E_DEFAULT = 1.0e6    # Young's modulus [Pa]
GATE_NU_DEFAULT = 0.0     # Poisson ratio [-]
GATE_RHO_DEFAULT = 2500.0  # density [kg/m^3]

# Gate mesh resolution used by 01_generate_mesh.py (matches 868 nodes / 540 C3D8).
GATE_NX, GATE_NY, GATE_NZ = 6, 30, 3

# Reference 1st natural frequency (Hz): paper table 3-2 / APDL mode 1.
EXPECTED_F1 = 6.018
TOLERANCE = 0.02  # 2 % relative tolerance on mode 1

CCX_EXE = "ccx"
JOBNAME = "dam_gate_modal"


# --------------------------------------------------------------------------- #
#  Small helpers                                                               #
# --------------------------------------------------------------------------- #

def fmt(x):
    """Compact float formatting for CalculiX ASCII files."""
    if isinstance(x, int):
        return str(x)
    return format(float(x), ".10g")


def split_values(line):
    """Split a CalculiX data line on commas or whitespace."""
    if "," in line:
        return [p.strip() for p in line.split(",") if p.strip()]
    return line.split()


# --------------------------------------------------------------------------- #
#  Mesh source 1: reuse 01_generate_mesh.py logic                                 #
# --------------------------------------------------------------------------- #

def load_generate_mesh(script_dir):
    """Import 01_generate_mesh from the script directory, or return None."""
    try:
        if script_dir not in sys.path:
            sys.path.insert(0, script_dir)
        return importlib.import_module("01_generate_mesh")
    except Exception:
        return None


# --------------------------------------------------------------------------- #
#  Mesh source 2: parse an existing dam_gate.inp                               #
# --------------------------------------------------------------------------- #

def parse_solid_inp(path):
    """Parse a CalculiX .inp into nodes/elements/nsets/material.

    Returns a dict with keys: coords (list), elements (list), nsets (dict),
    E, nu, rho (each possibly None when absent from the file).
    """
    coords = {}    # node_id -> (x, y, z)
    elements = {}  # elem_id -> (n1..n8)
    nsets = {}     # name -> [node ids]
    e_mod = nu = rho = None
    section = None

    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            line = raw.strip()
            if not line:
                continue
            if line.startswith("*"):
                sec = line.split(",")[0].strip()
                if sec == "*NODE":
                    section = "NODE"
                elif sec == "*ELEMENT":
                    section = "ELEMENT"
                elif sec == "*NSET":
                    section = "NSET:" + line.split("NSET=", 1)[1].split(",")[0].strip()
                elif sec == "*ELASTIC":
                    section = "ELASTIC"
                elif sec == "*DENSITY":
                    section = "DENSITY"
                else:
                    section = None
                continue

            if section == "NODE":
                p = split_values(line)
                coords[int(p[0])] = (float(p[1]), float(p[2]), float(p[3]))
            elif section == "ELEMENT":
                p = split_values(line)
                elements[int(p[0])] = tuple(int(n) for n in p[1:9])
            elif isinstance(section, str) and section.startswith("NSET:"):
                name = section.split(":", 1)[1]
                ids = [int(x) for x in line.rstrip(",").split(",") if x.strip()]
                nsets.setdefault(name, []).extend(ids)
            elif section == "ELASTIC":
                p = split_values(line)
                e_mod = float(p[0])
                nu = float(p[1])
            elif section == "DENSITY":
                p = split_values(line)
                rho = float(p[0])

    coords_list = [coords[i] for i in range(1, len(coords) + 1)]
    elements_list = [elements[i] for i in range(1, len(elements) + 1)]
    return {
        "coords": coords_list,
        "elements": elements_list,
        "nsets": nsets,
        "E": e_mod,
        "nu": nu,
        "rho": rho,
    }


# --------------------------------------------------------------------------- #
#  Mesh / material resolution                                                  #
# --------------------------------------------------------------------------- #

def resolve_mesh(mesh_dir, script_dir, gate_e, gate_nu, gate_rho):
    """Return (coords, elements, nsets, E, nu, rho, mesh_source)."""
    gm = load_generate_mesh(script_dir)
    parsed = None
    inp_path = os.path.join(mesh_dir, "dam_gate.inp")
    if os.path.isfile(inp_path):
        parsed = parse_solid_inp(inp_path)

    if gm is not None:
        coords, elements = gm.build_solid_mesh(GATE_NX, GATE_NY, GATE_NZ)
        nsets = gm.build_solid_nsets(GATE_NX, GATE_NY, GATE_NZ)
        mesh_source = "01_generate_mesh.build_solid_mesh(%d,%d,%d)" % (GATE_NX, GATE_NY, GATE_NZ)
    elif parsed is not None:
        coords = parsed["coords"]
        elements = parsed["elements"]
        nsets = parsed["nsets"]
        mesh_source = "parse dam_gate.inp"
    else:
        raise RuntimeError(
            "无法加载固体网格：既无法 import 01_generate_mesh，也不存在 %s" % inp_path
        )

    # Material: explicit CLI overrides win, then inp file, then defaults.
    e_mod = gate_e if gate_e is not None else (
        parsed["E"] if parsed is not None else GATE_E_DEFAULT)
    nu = gate_nu if gate_nu is not None else (
        parsed["nu"] if parsed is not None else GATE_NU_DEFAULT)
    rho = gate_rho if gate_rho is not None else (
        parsed["rho"] if parsed is not None else GATE_RHO_DEFAULT)

    return coords, elements, nsets, e_mod, nu, rho, mesh_source


# --------------------------------------------------------------------------- #
#  Modal .inp writer                                                           #
# --------------------------------------------------------------------------- #

def write_modal_inp(path, coords, elements, nsets, e_mod, nu, rho, n_modes):
    """Write the *FREQUENCY modal analysis deck (same BCs as dam_gate.inp)."""
    lines = []
    lines.append("** Dam-break gate modal analysis (C3D8), generated by run_modal_analysis.py")
    lines.append("*NODE")
    for nid, (x, y, z) in enumerate(coords, start=1):
        lines.append("%d, %s, %s, %s" % (nid, fmt(x), fmt(y), fmt(z)))

    lines.append("*ELEMENT, TYPE=C3D8, ELSET=Eall")
    for eid, conn in enumerate(elements, start=1):
        lines.append("%d, %s" % (eid, ", ".join(str(n) for n in conn)))

    for name in ("Nbottom", "Nzmin", "Nzmax"):
        nodes = nsets.get(name, [])
        if not nodes:
            continue
        lines.append("*NSET, NSET=%s" % name)
        for idx in range(0, len(nodes), 8):
            chunk = nodes[idx:idx + 8]
            lines.append(", ".join(str(n) for n in chunk) + ",")

    lines.append("*MATERIAL, NAME=GATE")
    lines.append("*ELASTIC")
    lines.append("%s, %s" % (fmt(e_mod), fmt(nu)))
    lines.append("*DENSITY")
    lines.append(fmt(rho))
    lines.append("*SOLID SECTION, ELSET=Eall, MATERIAL=GATE")
    lines.append("*STEP")
    lines.append("*FREQUENCY")
    lines.append("%d" % n_modes)
    lines.append("*BOUNDARY")
    lines.append("Nbottom, 1, 3, 0.0")
    lines.append("Nzmin, 3, 3, 0.0")
    lines.append("Nzmax, 3, 3, 0.0")
    lines.append("*END STEP")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


# --------------------------------------------------------------------------- #
#  ccx runner                                                                  #
# --------------------------------------------------------------------------- #

def run_ccx(out_dir, jobname):
    exe = shutil.which(CCX_EXE)
    if exe is None:
        raise RuntimeError("找不到 ccx 可执行文件（%s）" % CCX_EXE)
    proc = subprocess.run(
        [exe, "-i", jobname], cwd=out_dir,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
    )
    return proc


# --------------------------------------------------------------------------- #
#  Eigenvalue parsing                                                          #
# --------------------------------------------------------------------------- #

def _to_float(token):
    return float(token.replace("D", "E").replace("d", "e"))


def parse_eigenfrequencies(dat_path, n_modes):
    """Extract the first ``n_modes`` eigenfrequencies (Hz) from a ccx .dat.

    Handles the ccx 2.x eigenvalue table::

         MODE NO    EIGENVALUE                       FREQUENCY
                                             REAL PART            IMAGINARY PART
                                   (RAD/TIME)      (CYCLES/TIME     (RAD/TIME)

              1   0.1442652E+04   0.3798226E+02   0.6045065E+01   0.0000000E+00

    as well as the simpler ``<mode> <freq>`` two-column layout.
    """
    with open(dat_path, "r", encoding="utf-8", errors="replace") as fh:
        lines = fh.read().splitlines()

    freqs = []
    in_table = False
    for line in lines:
        compact = line.replace(" ", "")
        if not in_table:
            # table header: "MODE NO ... EIGENVALUE ... FREQUENCY"
            if "MODENO" in compact and "EIGENVALUE" in compact and "FREQUENCY" in compact:
                in_table = True
            continue

        s = line.strip()
        if not s:
            continue
        # stop at the next section header
        if ("PARTICIPATION" in s or "EFFECTIVE" in s or "MODAL" in s):
            break
        parts = s.split()
        if not parts or not parts[0].isdigit():
            continue  # skip sub-header lines like "REAL PART ..."
        mode = int(parts[0])
        try:
            if len(parts) == 5:
                # [mode, eigenvalue, rad/time, cycles/time(Hz), imag]
                hz = _to_float(parts[3])
            elif len(parts) >= 2:
                # [mode, freq(Hz)] simple layout
                hz = _to_float(parts[1])
            else:
                continue
        except ValueError:
            continue
        freqs.append(hz)
        if len(freqs) >= n_modes:
            break

    return freqs


# --------------------------------------------------------------------------- #
#  APDL reference frequency reader                                             #
# --------------------------------------------------------------------------- #

def read_reference_freqs(ref_dir, n_modes):
    """Read the APDL reference frequency from FluidNodeDisp<i>.csv headers."""
    freqs = []
    for i in range(1, n_modes + 1):
        path = os.path.join(ref_dir, "FluidNodeDisp%d.csv" % i)
        if not os.path.isfile(path):
            break
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            first = fh.readline()
        tok = first.split(",")[0].strip()
        freqs.append(_to_float(tok))
    return freqs


# --------------------------------------------------------------------------- #
#  Comparison table                                                            #
# --------------------------------------------------------------------------- #

def print_comparison(freqs_ccx, freqs_apdl):
    print("")
    print("阶数 | CalculiX (Hz) | APDL (Hz) | 相对误差 (%)")
    print("-----+---------------+-----------+-------------")
    n = min(len(freqs_ccx), len(freqs_apdl))
    for i in range(n):
        fc, fa = freqs_ccx[i], freqs_apdl[i]
        err = (fc - fa) / fa * 100.0
        print("%4d | %13.4f | %9.4f | %+11.2f" % (i + 1, fc, fa, err))
    print("")
    return n


# --------------------------------------------------------------------------- #
#  Main                                                                        #
# --------------------------------------------------------------------------- #

def parse_args(argv):
    p = argparse.ArgumentParser(
        description="CalculiX modal analysis of the dam-break gate + APDL "
                    "frequency comparison."
    )
    p.add_argument("--mesh-dir", default=MESH_DIR_DEFAULT,
                   help="solid mesh dir containing dam_gate.inp (default %s)"
                        % MESH_DIR_DEFAULT)
    p.add_argument("--out-dir", default=OUT_DIR_DEFAULT,
                   help="output dir for modal .inp/.dat (default %s)"
                        % OUT_DIR_DEFAULT)
    p.add_argument("--n-modes", type=int, default=10,
                   help="number of eigenmodes (default 10)")
    p.add_argument("--gate-e", type=float, default=None,
                   help="gate Young's modulus Pa (default: from inp or 1e6)")
    p.add_argument("--gate-nu", type=float, default=None,
                   help="gate Poisson ratio (default: from inp or 0)")
    p.add_argument("--gate-rho", type=float, default=None,
                   help="gate density kg/m3 (default: from inp or 2500)")
    p.add_argument("--ref-csv", default=REF_CSV_DEFAULT,
                   help="dir with FluidNodeDisp1..10.csv (default %s)"
                        % REF_CSV_DEFAULT)
    p.add_argument("--run-ccx", action="store_true", default=True,
                   help="run ccx (default True)")
    p.add_argument("--no-run-ccx", dest="run_ccx", action="store_false",
                   help="only generate the .inp, do not run ccx")
    return p.parse_args(argv)


def main(argv):
    args = parse_args(argv)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.abspath(args.out_dir)
    os.makedirs(out_dir, exist_ok=True)

    # ---- mesh + material ------------------------------------------------
    coords, elements, nsets, e_mod, nu, rho, mesh_source = resolve_mesh(
        args.mesh_dir, script_dir, args.gate_e, args.gate_nu, args.gate_rho)

    print("固体网格来源   : %s" % mesh_source)
    print("节点数         : %d" % len(coords))
    print("单元数         : %d (C3D8)" % len(elements))
    print("Nset           : Nbottom=%d, Nzmin=%d, Nzmax=%d" % (
        len(nsets.get("Nbottom", [])),
        len(nsets.get("Nzmin", [])),
        len(nsets.get("Nzmax", [])),
    ))
    print("材料参数       : E=%.6g Pa, nu=%.6g, rho=%.6g kg/m^3" % (e_mod, nu, rho))

    # ---- write modal inp -------------------------------------------------
    inp_path = os.path.join(out_dir, JOBNAME + ".inp")
    write_modal_inp(inp_path, coords, elements, nsets, e_mod, nu, rho, args.n_modes)
    print("已生成模态分析 .inp : %s" % inp_path)

    # ---- run ccx ----------------------------------------------------------
    if not args.run_ccx:
        print("--run-ccx=False：仅生成 inp，跳过 ccx 求解。")
        return 0

    proc = run_ccx(out_dir, JOBNAME)
    dat_path = os.path.join(out_dir, JOBNAME + ".dat")
    if proc.returncode != 0:
        print("ERROR: ccx 运行失败 (rc=%d)" % proc.returncode)
        print(proc.stdout)
        print(proc.stderr)
        if os.path.isfile(dat_path):
            print(open(dat_path, "r", encoding="utf-8", errors="replace").read()[-2000:])
        return 1
    print("ccx 运行成功 (rc=0)，输出 %s" % dat_path)

    # ---- parse eigenfrequencies ------------------------------------------
    freqs_ccx = parse_eigenfrequencies(dat_path, args.n_modes)
    if len(freqs_ccx) < 1:
        print("ERROR: 未能从 %s 解析出特征值。" % dat_path)
        return 1
    print("解析到 %d 阶频率：" % len(freqs_ccx))
    for i, f in enumerate(freqs_ccx, start=1):
        print("  第 %2d 阶 : %.6f Hz" % (i, f))

    # ---- reference --------------------------------------------------------
    freqs_apdl = read_reference_freqs(args.ref_csv, args.n_modes)
    if not freqs_apdl:
        print("WARNING: 未在 %s 找到 FluidNodeDisp*.csv，跳过对比。" % args.ref_csv)
        return 0

    print_comparison(freqs_ccx, freqs_apdl)

    # ---- assert mode 1 ----------------------------------------------------
    f1 = freqs_ccx[0]
    ref1 = freqs_apdl[0]
    rel = abs(f1 - ref1) / abs(ref1)

    if rel < TOLERANCE:
        print("PASS: 一阶频率 %.4f Hz 与基准 %.4f Hz 相对误差 %.2f%% (< 2%%)" %
              (f1, ref1, rel * 100.0))
        return 0

    print("WARNING: 一阶频率 %.4f Hz 与基准 %.4f Hz 相对误差 %.2f%% (>= 2%%)" %
          (f1, ref1, rel * 100.0))
    if f1 < ref1 * 0.75:
        print("提示：偏差较大，材料参数可能与本算例基准不符。")
        print("      本算例正确参数为 E=1e6 Pa / nu=0 / rho=2500 kg/m^3")
        print("      （对应一阶 ~6.02 Hz，而非 ~3.6 Hz 等错误材料组合）。")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
